<?php
return [
  'appointments_service_appointmentsmenu' => 'Appointments\Factory\Service\AppointmentsMenuFactory',
  'Appointments\Service\AppointmentsMenu' => 'Appointments\Factory\Service\AppointmentsMenuFactory',
  Appointments\Service\AppointmentsMenu::class => Appointments\Factory\Service\AppointmentsMenuFactory::class,
  'appointments_service_appointments' => 'Appointments\Factory\Service\AppointmentsFactory',
  'Appointments\Service\Appointments' => 'Appointments\Factory\Service\AppointmentsFactory',
  Appointments\Service\Appointments::class => Appointments\Factory\Service\AppointmentsFactory::class,
  'Appointments\Model\AppointmentsUsersTable' => 'Appointments\Factory\Model\AppointmentsUsersTableFactory',
  Appointments\Model\AppointmentsUsersTable::class => Appointments\Factory\Model\AppointmentsUsersTableFactory::class,
  'Appointments\Model\AppntProviderTable' => 'Appointments\Factory\Model\AppntProviderTableFactory',
  Appointments\Model\AppntProviderTable::class => Appointments\Factory\Model\AppntProviderTableFactory::class,
  'Appointments\Model\AppntProvider' => 'Appointments\Factory\Model\AppntProviderFactory',
  Appointments\Model\AppntProvider::class => Appointments\Factory\Model\AppntProviderFactory::class,
  'Appointments\Model\ProviderServices' => 'Appointments\Factory\Model\ProviderServicesFactory',
  Appointments\Model\AppntProviderService::class => Appointments\Factory\Model\ProviderServicesFactory::class,
  'Appointments\Model\AppntProviderService' => 'Appointments\Factory\Model\AppntProviderServiceFactory',
  Appointments\Model\AppntProviderService::class => Appointments\Factory\Model\AppntProviderServiceFactory::class,
  'Appointments\Model\Provider' => 'Appointments\Factory\Model\ProviderFactory',
  Appointments\Model\Provider::class => Appointments\Factory\Model\ProviderFactory::class,
  'Appointments\Model\AppntHealthFacilityTable' => 'Appointments\Factory\Model\AppntHealthFacilityTableFactory',
  Appointments\Model\AppntHealthFacilityTable::class => Appointments\Factory\Model\AppntHealthFacilityTableFactory::class,
  'Appointments\Model\AppntProviderServiceTable' => 'Appointments\Factory\Model\AppntProviderServiceTableFactory',
  Appointments\Model\AppntProviderServiceTable::class => Appointments\Factory\Model\AppntProviderServiceTableFactory::class,
  'Appointments\Model\ProviderServicesTable' => 'Appointments\Factory\Model\ProviderServicesTableFactory',
    Appointments\Model\AppntProviderService::class => Appointments\Factory\Model\ProviderServicesTableFactory::class,
  'Appointments\Model\ProviderTable' => 'Appointments\Factory\Model\ProviderTableFactory',
  Appointments\Model\ProviderTable::class => Appointments\Factory\Model\ProviderTableFactory::class,
  'Appointments\Model\Users' => 'Appointments\Factory\Model\UsersFactory',
  Appointments\Model\Users::class => Appointments\Factory\Model\UsersFactory::class,
  'Appointments\Model\AppntHealthFacility' => 'Appointments\Factory\Model\AppntHealthFacilityFactory',
  Appointments\Model\AppntHealthFacility::class => Appointments\Factory\Model\AppntHealthFacilityFactory::class
];
