zf:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8000:80"
  volumes:
   - .:/var/www

php:
  image: php:7.2


mysql:
  image: mysql:latest
  expose:
      - 3306
  volumes:
      - database_data:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: Malio@123
      MYSQL_DATABASE: stoneweb_developer
      MYSQL_USER: root
      MYSQL_PASSWORD: stoneweb_developer
db:
  image: postgres
  expose:
    - 5432
  restart: always
  environment:
    POSTGRES_PASSWORD: malio1234
    POSTGRES_DATABASE: maps
    POSTGRES_USER: postgres
    
adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080

apache:
  image: httpd:2.4

        