<?php /* @var $this \Zend\View\Renderer\PhpRenderer */?>
<div class="panel panel-default">
	<div class="anchor_login_form">
		<div class="page-header">
			<h3 class="stone-darkslategray-title">Set New Password</h3>
		</div>
		<div class="panel-body">
        <?php echo $this->partial('flash/flashMessages');?>
        <?php echo $this->partial('forms/users/userSetPassword');?>
        </div>
	</div>
</div>
