<?php
// module/Album/view/album/album/add.phtml:

$title = 'Book Appointment';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('appointments', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

echo $this->formRow($form->get('firstname'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Name');

echo $this->formRow($form->get('secondname'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Name');

echo $this->formRow($form->get('gender'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Gender');

echo $this->formRow($form->get('phonenumber'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Phone number');

echo $this->formRow($form->get('email'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Email address');

echo $this->formRow($form->get('hospital'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Hopital Name');

echo $this->formRow($form->get('date'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Date');

echo $this->formRow($form->get('specialty'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Doctors specialization');

echo $this->formRow($form->get('time'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'time');

echo $this->formRow($form->get('reason'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'reason for appoinment');

echo $this->formSubmit($form->get('submit'));
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Submit');
echo $this->form()->closeTag();

