<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new appointment';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('appointment', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('fname'));
echo $this->formRow($form->get('lname'));
echo $this->formRow($form->get('gender'));
echo $this->formRow($form->get('phone_number'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('hospital'));
echo $this->formRow($form->get('speciality'));
echo $this->formRow($form->get('appointment_date'));
echo $this->formRow($form->get('appointment_time'));
echo $this->formRow($form->get('reason'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();