<div class="anchor_login_form">
	<div class="page-header">
		<h3 class="stone-darkslategray-title"><?php echo sprintf($this->translate('Sign In')); ?></h3>
	</div>
<?php echo $this->partial('forms/user/userLoginForm');?>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "200px";
}
/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>
</div>
