


<div id="mapid"></div>

<div id="main"></div>
       

 <script>

 $( document ).ready(function() {
		
	    console.log( "ready!" );
	    
	    var mymap = L.map('mapid').setView([3.121832846, 35.587164318], 13);
	    
	    $(document).ready(initialize);
	    function initialize(){
	    L.tileLayer('https://external.fnbo4-1.fna.fbcdn.net/map_tile.php?v=29&x={x}&y={y}&z={z}&language=en_GB?access_token={pk.eyJ1Ijoia2FuaW5pbWFsaW8iLCJhIjoiY2poamh4ZjllMDB4ZTM2cWtoM2V3bWd1ZyJ9.rnF81uaCjIFtaEAfQ1ytBg}', {
	        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">KenyaHealthFacilitiess</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
	        maxZoom: 18,
	        id: 'mapbox.streets',
	        accessToken: 'pk.eyJ1Ijoia2FuaW5pbWFsaW8iLCJhIjoiY2poamh4ZjllMDB4ZTM2cWtoM2V3bWd1ZyJ9.rnF81uaCjIFtaEAfQ1ytBg'
	    }).addTo(mymap);
	    }
	    var popup = L.popup()
	    .setLatLng([3.121832846, 35.587164318])
	    .setContent("I am a standalone popup.")
	    .openOn(mymap);
	    
	   
         

                

        var markers = [
        	<?php foreach ($hospitals as $stonelink) : ?>
        	[<?= $this->escapeHtml($stonelink->latitude)?>,  <?= $this->escapeHtml($stonelink->longitude)?>, "<?= $this->escapeHtml($stonelink->facility_n)?>"],
        	<?php endforeach; ?>
        			];

        var markerClusterGroup = L.markerClusterGroup();

        for (var i = 0; i < markers.length; i++) {
        	var a = markers[i];
        	var title = a[2];
        	var marker = L.marker(new L.LatLng(a[0], a[1]), { title: title });
        	marker.bindPopup(title);
        	markerClusterGroup.addLayer(marker);
        }

        mymap.addLayer(markerClusterGroup);
	    var popup = L.popup();
	    function onMapClick(e) {
	        popup
	            .setLatLng(e.latlng)
	            .setContent("You clicked the map at " + e.latlng.toString())
	            .openOn(mymap);
	    }
	    mymap.on('click', onMapClick);
	    function getData(){
	    	$.ajax("/config/local.php", {
	    		data: {
	    			table: "Kenya_maps_2015_health_facilities",
	    			fields: fields
	    		},
	    		success: function(data){
	    			mapData(data);
	    		}
	    	})
	    };
	    function mapData(data){
	    	//remove existing map layers
	    	map.eachLayer(function(layer){
	    		//if not the tile layer
	    		if (typeof layer._url === "undefined"){
	    			map.removeLayer(layer);
	    		}
	    	});
	    }
	    //create geojson container object
	    var geojson ={ 
	    	"type": "FeatureCollection",
	    	"features": []
	    };
	});
	
	 function openNav() {
	    document.getElementById("mySidenav").style.width = "200px";
	}
	/* Set the width of the side navigation to 0 */
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}

 </script>