<div id="mapid" class="mt-0"></div>
<div id="form" class="navbar"></div>
<div id="main"></div>
<div class="menu-button" id="menu-button"></div>

<script>
function initMap() {
var myLatLng = {lat: -1.2921, lng: 36.8219};
var mapProp= {
    center:myLatLng,
    zoom:7,
};
var map=new google.maps.Map(document.getElementById("mapid"),mapProp);

// var image =  {
// 	url:"http://ajali.afyaresearch.org/images/hospital.png"
// 	size: new google.maps.Size(20, 32),
// }
var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    
    title: 'Hello World!'
  });
var markers = [
 	<?php foreach ($hospitals as $stonelink) : ?>
     	[<?= $this->escapeHtml($stonelink->latitude)?>, 
     	 <?= $this->escapeHtml($stonelink->longitude)?>, 
     	 "<?= $this->escapeHtml($stonelink->facility_n)?>", 
     	 "<?= $this->escapeHtml($stonelink->county)?>",
     	 "<?= $this->escapeHtml($stonelink->type)?>",
     	 "<?= $this->escapeHtml($stonelink->owner)?>"
     	 ],
 	<?php endforeach; ?>
	];

for (var i = 0; i < markers.length; i++) {
 	var a = markers[i];
 	var title = 'Name:'+' '+ a[2]+'<br>'+'County:'+ ' '+ a[3]+'<br>'+'Type:'+' ' + a[4]+'<br>'+ 'Owner:'+' ' +a[5];
 	var marker = new google.maps.Marker({
 	      position: myLatLng,
 	 	//icon:image,
 	      map: map,
 	      title: a[0],
 	    });
}
marker.setMap(map);
}
//for the nav bar
function openNav() {
	    document.getElementById("mySidenav").style.width = "200px";
	}

	/* Set the width of the side navigation to 0 */
function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}
</script>
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHj5_T9nC7gQrQbdHyY1MAbck6lxLuJDk&callback=initMap">
</script>