<?php
/**
* This file is automatically generated- do not edit manually
*
* StoneHMIS (http://stonehmis.afyaresearch.org/)
*
* @link      http://github.com/stonehmis/stone for the canonical source repository
* @copyright Copyright (c) 2009-2018 Afya Research Africa Inc. (http://www.afyaresearch.org)
* @license   http://stonehmis.afyaresearch.org/license/options License Options
*/

return [
  'stonechat_service_stonechat' => 'Stonechat\Factory\Service\StonechatFactory',
  'Stonechat\Service\Stonechat' => 'Stonechat\Factory\Service\StonechatFactory',
  Stonechat\Service\Stonechat::class => Stonechat\Factory\Service\StonechatFactory::class,
  'Stonechat\Model\AuthenticationService' => 'Stonechat\Factory\Model\AuthenticationServiceFactory',
  'Stonechat\Model\RegPersonTable' => 'Stonechat\Factory\Model\RegPersonTableFactory'
];
