<?= $this->doctype() ?>



<html lang="en">
    <head>
        <meta charset="utf-8">
               <link rel= "manifest" href="/manifest.json">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">


<link rel="manifest" href="/img/site.webmanifest">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
   integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
   crossorigin=""/>

<link rel="mask-icon" href="/img/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/img/favicon.ico">
<link rel="stylesheet" type="text/css" href="css/style.css" media="screen, handheld" media="screen  and (min-width: 40.5em)" />

<meta name="apple-mobile-web-app-title" content="Stoneweb">
<meta name="application-name" content="Stoneweb">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/img/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
   integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
   crossorigin=""></script>
<!-- <script -->
<!-- 	 src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" -->
<!--     async defer> -->

<!-- </script> -->

        <?= $this->headTitle('stoneweb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
            ->appendName('viewport', 'width=device-width, initial-scale=1' )
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
      
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/MarkerCluster.css'))
            ->prependStylesheet($this->basePath('css/leaflet-marker-cluster.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/leaflet-marker-cluster.js'))
        ?>
    </head>
    <body class = "html">
        <nav class="navbar navbar-color navbar-fixed-top " role="navigation">
            <div class="container">
                
                <div class="sidenav "  id="mySidenav" >
                <a href="javascript:void(0)" style="color:black;"class="closebtn" onclick="closeNav()">&times;</a>
                    <ul class="nav  navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav ">
                        <li class="active"><a href="<?=$this->url('stonelink/stonelink', array('action' => 'add'));?>">Book Appointment</a></li>
                    </ul>
                     <ul class="nav navbar-nav ">
                        <li class="active"><a href="<?= $this->url('home') ?>">Search Clinician</a></li>
                    </ul>
                </div>
                <span class= "navbar-left navbar-sticks" onclick="openNav()">&#9776;</span>
               
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Afya Research Africa. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>