
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<link rel="manifest" href="/manifest.json">
<link rel="apple-touch-icon" sizes="180x180"
	href="/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32"
	href="/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16"
	href="/img/favicon-16x16.png">


<link rel="manifest" href="/img/site.webmanifest">


<link rel="shortcut icon" href="/img/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Stoneweb">
<meta name="application-name" content="Stoneweb">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/img/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

        <?=$this->headTitle('stoneweb')->setSeparator(' - ')->setAutoEscape(false)?>
        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')->appendName('viewport', 'width=device-width, initial-scale=1')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
        <meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

<!-- Le styles -->
        <?=$this->headLink(['rel' => 'shortcut icon','type' => 'image/vnd.microsoft.icon','href' => $this->basePath() . '/img/favicon.ico'])->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))->prependStylesheet($this->basePath('css/bootstrap.min.css'))->prependStylesheet($this->basePath('css/style.css'))?>
        <!-- Scripts -->
        <?=$this->headScript()->prependFile($this->basePath('js/bootstrap.min.js'))->prependFile($this->basePath('js/jquery-3.1.0.min.js'))->prependFile($this->basePath('js/app.js'))?>

    </head>

<body class="html mt-0">
<div class="margin"></div>
<?= $this->doctype() ?>
	<nav class="navbar navbar-color navbar-fixed-top " role="navigation">
		<div class="container">
			<div class="sidenav " id="mySidenav">
				<a href="javascript:void(0)"  style="padding:10px 3px 10px 3px;display:inline:block;margin-bottom: 10px; padding: 15px;color: black; font-size: 30px; margin-left: 150px;" onclick="closeNav()">&times;</a>
				<ul class="  navbar-nav">
					<li class="active"><a
						href="<?=$this->url('stonelink/stonelink', array('action' => 'index'));?>">View
							Hopitals</a></li>
				</ul>
				<ul class="navbar-nav ">
					<li class="active"><a
						href="//easyappointments.localhost/index.php">Book
							Appointment</a></li>
				</ul>
				<ul class=" navbar-nav ">
					<li class="active"><a href="https://stonechat.net/">Talk to
							Somebody</a></li>

				</ul>
				<ul class="navbar-nav ">
					<li class="active"><a
						href="<?=$this->url('stonelink/stonelink', array('action' => 'search'));?>">Search
							Clinic </a></li>
				</ul>

			
			</div>
			<span class="navbar-left navbar-sticks" onclick="openNav()">&#9776;</span>

		</div>
	</nav>

	<div class="container">
            <?= $this->content ?>
            <hr>

	</div>
	<footer>
		<p>&copy; 2005 - <?= date('Y') ?> by Afya Research Africa. All rights reserved.</p>
	</footer>
        <?= $this->inlineScript() ?>
    </body>
</html>