<?php /* @var $this \Zend\View\Renderer\PhpRenderer */?>
<div class="row">
	<div class="col-md-offset-3 col-md-5">
		<h1 class='text-info text-center'>Reset Password</h1>
        <?php if ($this->id=='sent'): ?>
        		<div class="alert alert-info" role="info">
			<p>Password reset instructions have been sent to your email address.</p>
			<p>Remember to check your BULK or SPAM folders</p>
		</div>
        <?php elseif ($this->id=='invalid-email'): ?>
        		<div class="alert alert-danger" role="danger">
			<p>There is no user with such an email or the user is inactive.</p>
		</div>
        <?php elseif ($this->id=='set'): ?>
        		<div class="alert alert-success" role="success">
			<p>
				Your new password has been set successfully. Please <a
					href="<?php echo $this->url('login'); ?>">login</a>.
			</p>
		</div>
        <?php elseif ($this->id=='failed'): ?>
        		<div class="alert alert-warning" role="alert">
			<p class="text-center">
				Invalid or expired reset key. <a
					href="<?php echo $this->url('resetpassword') ?>">Reset Password</a>.
			</p>
		</div>
        <?php endif; ?>
    </div>
</div>
