<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
foreach ($form as $element) {
    $this->partial()->setObjectKey('element');
    echo $this->partial('formWidgets/oneColumnForm', $element);
}
$this->partial()->setObjectKey('form');
echo $this->partial('formWidgets/oneColumnFormButton', $form);
echo $this->form()->closeTag();