<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
               <link rel= "manifest" href="/manifest.json">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">


<link rel="manifest" href="/img/site.webmanifest">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
   integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
   crossorigin=""/>

<link rel="mask-icon" href="/img/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/img/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Stoneweb">
<meta name="application-name" content="Stoneweb">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/img/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
   integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
   crossorigin=""></script>
<!-- <script -->
<!-- 	 src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" -->
<!--     async defer> -->

<!-- </script> -->


        
        <?= $this->headTitle('stoneweb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
      
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/app.js'))
           
            
        ?>
    </head>
    <body>
        <nav class="navbar navbar-color navbar-fixed-top text-body" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  
                </div>
                <div class="collapse navbar-collapse navbar-left text-body ">
                    <ul class="nav  navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">HomeHome</a></li>
                    </ul>
                     <ul class="nav navbar-nav ">
                        <li class="active"><a href="<?= $this->url('home') ?>">Stonelink</a></li>
                    </ul>
                     <ul class="nav navbar-nav ">
                        <li class="active"><a href="<?= $this->url('home') ?>">Stonechat</a></li>
                    </ul>
                </div>
                
                 <div>
                <ul class="nav navbar-nav navbar-right ">
                  <li><a href="#"><span class="glyphicon glyphicon-user active"></span> Sign Up</a></li>
                  <li><a href="#"><span class="glyphicon glyphicon-log-in active" ></span> Sign In</a></li>
    			</ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Afya Research Africa. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
