<div id="form" class="margin" ></div>

<?php
$title = 'Appointment';
$this->headTitle($title);
?>
<head>
<div style = "color: black; font-size:30px; text-align: center;">Enter Person Details</div>
</head>
<?php

$form->setAttribute('action', $this->url('appointments', ['appointments' => 'addpersondetails'
]));

$form->prepare();

$first_name = $form->get('first_name');
$first_name->setAttribute('class', 'form-control');
$first_name->setAttribute('placeholder', 'First Name');
$first_name->setAttribute('type', 'required');

$second_name = $form->get('second_name');
$second_name->setAttribute('class', 'form-control');
$second_name->setAttribute('placeholder', 'Last Name');

$phone_number = $form->get('phone_number');
$phone_number->setAttribute('class', 'form-control');
$phone_number->setAttribute('placeholder', 'Phone Number');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email Address');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($first_name) ?>
    <?= $this->formElement($first_name) ?>
    <?= $this->formElementErrors()->render($first_name, ['class' => 'help-block']) ?>
</div>

	<div class="form-group">
    <?= $this->formLabel($second_name) ?>
    <?= $this->formElement($second_name) ?>
    <?= $this->formElementErrors()->render($second_name, ['class' => 'help-block']) ?>
</div>


	<div class="form-group">
    <?= $this->formLabel($phone_number) ?>
    <?= $this->formElement($phone_number) ?>
    <?= $this->formElementErrors()->render($phone_number, ['class' => 'help-block']) ?>
</div>

	<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>



<?php
echo $this->formSubmit($submit);

echo $this->form()->closeTag();
?>
<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "200px";
}
/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>