<head>
<div style="color: black; font-size: 30px; text-align: center;">Please
	confirm the details</div>
</head>

<div style="text-align: center">

	<div>
		<b>Name</b>: Sharon Malio
	</div>
	<div>
		<b>Date/Time</b>: 13th, November 2018
	</div>
	<div>
		<b>Service</b>: Skin Allergies
	</div>
	<div>
		<b>Provider</b>: Sharon Malio
	</div>
	<div>
		<b>Amount</b>: Ksh.30
	</div>
	<div style="width:500px; margin:0 auto;">
        <div class= "row">
			<a href="pay" class=" btn btn-primary btn-block"
				> Confirm</a>
	</div>
    </div>

</div>
<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "200px";
}
/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>