<div class="jumbotron">
    <h1>Welcome to <span class="">Stoneweb</span></h1>

    <p>
        With <a href="" target="_blank">Stoneweb</a>, you can view all the available clinics in Kenya.
        Stoneweb has a platform for that enables anonimous commuication to a health specialist enabling the parties to talk with the goal of serving the patients. 
        Patients are able to <a href="">book an appointment</a> as well as pay for the service and rate the health specialists as well
     	Our main goal is to provide the platform to enable easy interactions between a patient and a clinician.    
    </p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">About Stoneweb</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stonelink</h3>
            </div>
            <div class="panel-body">
                
 				<p>
                                   
                </p>
                
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stonechat</h3>
            </div>
            <div class="panel-body">
                <p>
                                   
                </p>
<script type="text/javascript">

function openNav() {
	    document.getElementById("mySidenav").style.width = "200px";
	}

	/* Set the width of the side navigation to 0 */
function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}
</script>
            </div>
        </div>
    </div>
</div>
