<?php
/**
* This file is automatically generated- do not edit manually
*
* StoneHMIS (http://stonehmis.afyaresearch.org/)
*
* @link      http://github.com/stonehmis/stone for the canonical source repository
* @copyright Copyright (c) 2009-2018 Afya Research Africa Inc. (http://www.afyaresearch.org)
* @license   http://stonehmis.afyaresearch.org/license/options License Options
*/

return [
  'stonelink_service_stonelink' => 'Stonelink\Factory\Service\StonelinkFactory',
  'Stonelink\Service\Stonelink' => 'Stonelink\Factory\Service\StonelinkFactory',
  Stonelink\Service\Stonelink::class => Stonelink\Factory\Service\StonelinkFactory::class,
  'Stonelink\Model\AppointmentTable' => 'Stonelink\Factory\Model\AppointmentTableFactory',
  'Stonelink\Model\KenyaMaps2015HealthFacilitiesTable' => 'Stonelink\Factory\Model\KenyaMaps2015HealthFacilitiesTableFactory',
  'Stonelink\Model\ProviderTable' => 'Stonelink\Factory\Model\ProviderTableFactory'
];
