<?php
namespace Stonelink;
/**
* This file is automatically generated- do not edit manually
*
* StoneHMIS (http://stonehmis.afyaresearch.org/)
*
* @link      http://github.com/stonehmis/stone for the canonical source repository
* @copyright Copyright (c) 2009-2018 Afya Research Africa Inc. (http://www.afyaresearch.org)
* @license   http://stonehmis.afyaresearch.org/license/options License Options
*/

return [
  
  Controller\ProvidersController::class => Factory\Controller\ProvidersControllerFactory::class,
  Controller\StonelinkController::class => Factory\Controller\StonelinkControllerFactory::class
];
