<div class="jumbotron">
    <h1>Welcome to Stoneweb</h1>

    <p>
        Welcome to stoneweb. 
        You can book online appointments with your doctors and Connect with anyone you with to as well as chat with any doctor you would wish to. 
        On the top left of this page, we have the menu that guides you through navigating this website. Kindly make use of it. 
    </p>

    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stoneweb</h3>
            </div>
            <div class="panel-body">
                <p>
                 This is the combination of both stonelink and stonechat that is borrowed from the StoneHMIS platform. 
                 The term refers to the website version of the StoneHMIS platform that enables specialists
                 to take care of the patients digitally and in a systematic way 
                </p>

                <p><a class="btn btn-primary pull-right zf-green "   href="//stonewebdev.localhost/stonelink/stonelink/" target="_blank">Stoneweb</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stonelink</h3>
            </div>
            <div class="panel-body">
                <p>
                  Shows a network of the available registered hospitals in Kenya displayed on a map for easy visualization.
                  This platform enables one identify the hospitals near them and those that they might be interested into. 
                </p>

                <p><a class="btn btn-primary pull-right zf-green"   href="//stonewebdev.localhost/stonelink/stonelink/" target="_blank">Stonelink</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stonechat</h3>
            </div>
            <div class="panel-body">
                <p>
                   If you need any help or talking to any specialist or a colleague. We have a platform called <a href="https://stonechat.net/" target="_blank">Stonechat</a> for you.
                   Please ensure that you register and post any burning questions in the platform. Use the button below to visit the page
                </p>

                <p><a class="btn btn-primary pull-right " href="https://stonechat.net/" target="_blank">Stonechat</a></p>
            </div>
        </div>
    </div>
      <script type="text/javascript">//for the nav bar
function openNav() {
	    document.getElementById("mySidenav").style.width = "200px";
	}
	/* Set the width of the side navigation to 0 */
function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}</script>
</div>
