<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('users/user', array(
    'action' => 'register'
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
foreach ($form as $element) {
    $this->partial()->setObjectKey('element');
    echo $this->partial('formWidgets/oneColumnForm', $element);
}
$this->partial()->setObjectKey('form');
echo $this->partial('formWidgets/oneColumnFormButton', $form);
echo $this->form()->closeTag();