<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$this->form->prepare();
$this->form->setAttribute('action', $this->url('login'));
$this->form->setAttribute('method', 'post');
echo $this->form()->openTag($this->form);
foreach ($this->form as $element) {
    $this->partial()->setObjectKey('element');
    echo $this->partial('formWidgets/oneColumnForm', $element);
}
?>
<input type="hidden" name="redirect"
	value="<?php echo $this->escapeHtml($this->redirect_url); ?>" />
<?php
$this->partial()->setObjectKey('form');
echo $this->partial('formWidgets/oneColumnFormButton', $this->form);
echo $this->form()->closeTag();
?>
<br>
<br>